### ISSUE TITLE
目前 IPV6 没有分流

### ISSUE THREAD

**Issue by AxIauk** [yangchuansheng/love-gfw#2]
首先非常感谢你的脚本，运行很好。
我的笔记本使用 debian 9+iptables+Pcap_DNSProxy 支持IPV4和IPV6，服务器同时支持 IPV4和IPV6。
问题是ipv4做了分流，ipv6都是直连。 
访问网站时似乎 ipv6 优先，导致很多网站依然无法打开。 curl -4 google.com可以访问，curl -6 google.com失败。目前我只能强制关闭IPV6. 希望能完善脚本。

**Comment by yangchuansheng** [comment]
暂时没有考虑 ipv6 的流量，后续我会完善

**Comment by AxIauk** [comment]
感谢
