### ISSUE TITLE
可以考虑使用中科大的无污染DNS服务器

### ISSUE THREAD

**Issue by huangwenshan1999** [yangchuansheng/love-gfw#3]
在配置DNS服务器的环节，如果图方便的话可以考虑使用中科大的DNS服务器，目前我得知有两个服务器可以使用，分别是：
1.教育网： 202.38.93.153
2.电信: 202.141.162.123
我用这两个服务器在查询twitter.com域名时得到的ip和使用dnscrypt-proxy查询的结果如下:
(1).dnscrypt-proxy查询
root@Debian:/home/huang# nslookup www.twitter.com 127.0.2.1
Server:		127.0.2.1
Address:	127.0.2.1#53

Non-authoritative answer:
www.twitter.com	canonical name = twitter.com.
Name:	twitter.com
Address: 104.244.42.1
Name:	twitter.com
Address: 104.244.42.65
(2).中科大的DNS查询
root@Debian:/home/huang# nslookup www.twitter.com 202.38.93.153
Server:		202.38.93.153
Address:	202.38.93.153#53

Non-authoritative answer:
www.twitter.com	canonical name = twitter.com.
Name:	twitter.com
Address: 104.244.42.129
Name:	twitter.com
Address: 104.244.42.65
################################
root@Debian:/home/huang# nslookup www.twitter.com 202.141.162.123
Server:		202.141.162.123
Address:	202.141.162.123#53

Non-authoritative answer:
www.twitter.com	canonical name = twitter.com.
Name:	twitter.com
Address: 104.244.42.65
Name:	twitter.com
Address: 104.244.42.129

**Comment by yangchuansheng** [comment]
多谢，我稍后整合到文档中
